# -*- coding: utf-8 -*-
import json
from pathlib import Path

ROOT = Path(r"D:\chatgpt\mbti-test")


def q(id_, axis, kicker, text, quote, options):
    return {
        "id": id_,
        "axis": axis,
        "kicker": kicker,
        "text": text,
        "quote": quote,
        "options": options,
    }


def o(value, zh, en, hz, he):
    return {
        "value": value,
        "label": {"zh": zh, "en": en},
        "hint": {"zh": hz, "en": he},
    }


def qq(zh, en):
    return {"zh": zh, "en": en}


QUESTIONS = [
    q(1, "EI", qq("电梯社死赛 · E/I", "Elevator Cringe Cup · E/I"),
      qq("电梯只剩你和老板，空气开始发霉。你会？", "Just you and the boss in an elevator. The air is rotting. You:"),
      qq("金句：尴尬不会杀死人，但会让人练出影分身。", "Quote: Awkwardness rarely kills; it just unlocks clone mode."),
      [o("E", "硬聊天气，再把季度目标硬塞进去", "Force weather talk, then smuggle in quarterly goals", "社牛续命", "Social CPR"),
       o("I", "盯楼层数字，像看人生进度条", "Stare at floor numbers like a life loading bar", "隐身术MAX", "Stealth max"),
       o("E", "冷笑话开局：电梯停了算加班吗", "Cold joke: if it stops, is it overtime?", "幽默拆弹", "Humor defuse"),
       o("I", "戴耳机假装在开董事会", "Headphones on, fake a board meeting", "战术耳塞", "Tactical buds")]),
    q(2, "SN", qq("创业滤镜 · S/N", "Startup Filter · S/N"),
      qq("朋友说“我有个绝妙创业点子”，你第一句？", "Friend: “Genius startup idea.” Your first line?"),
      qq("金句：点子很便宜，执行才是付费会员。", "Quote: Ideas are free; execution is the paid plan."),
      [o("S", "成本多少？谁付钱？三个月能活吗？", "Cost? Who pays? Survive 3 months?", "现实重锤", "Reality hammer"),
       o("N", "名字呢？世界观呢？周边能卖吗？", "Name? Lore? Merch potential?", "脑内融资", "Imagination VC"),
       o("S", "先把竞品链接和避雷清单发我", "Send competitors + red-flag list first", "市场审计怪", "Market auditor"),
       o("N", "我已经脑补上市敲钟和纪录片旁白了", "Already casting IPO bell + documentary VO", "预演成功", "Success trailer")]),
    q(3, "TF", qq("深夜树洞 · T/F", "1AM Vent · T/F"),
      qq("朋友 1:17 发来“我好烦啊啊啊”，你回？", "1:17am text: “I’m SO done.” You reply:"),
      qq("金句：有人要方案，有人要回血包，先确认模式再输出。", "Quote: Some need a plan, some need a heal pack—confirm mode first."),
      [o("T", "发生了什么？给你三个可执行选项", "What happened? Three actionable options inbound", "问题解决机", "Fix-it bot"),
       o("F", "先抱抱。你委屈了，我在", "Hug first. You’re hurt. I’m here.", "情绪急救", "Emotion EMS"),
       o("T", "先把时间线理清，别让情绪绑架逻辑", "Timeline first—don’t let feelings kidnap logic", "冷静拆弹", "Calm defuse"),
       o("F", "先一起骂两句，再慢慢哄", "Rant together first, comfort later", "搭子安慰", "Buddy comfort")]),
    q(4, "JP", qq("周末人设 · J/P", "Weekend Persona · J/P"),
      qq("周六醒来，你的默认模式是？", "Saturday morning default mode:"),
      qq("金句：计划是理想国，沙发是现实政权。", "Quote: Plans are utopia; the sofa is the real government."),
      [o("J", "打开清单：洗衣/健身/学习分段执行", "Open checklist: laundry/gym/study blocks", "日程主神", "Calendar deity"),
       o("P", "先刷一小时，看运气掉落什么任务", "Scroll one hour; let RNG drop a quest", "随机事件", "Random event"),
       o("J", "早餐时间都排好了，偏差15分钟就焦虑", "Breakfast timed; 15-min drift = anxiety", "精度控", "Precision freak"),
       o("P", "计划写了，真正决定权在沙发", "Plan exists; sofa holds veto power", "沙发执政", "Couch cabinet")]),
    q(5, "EI", qq("局后电量 · E/I", "Afterparty Battery · E/I"),
      qq("饭局散场，你走在路上最真实的想法？", "Dinner ends. Walking out, your real thought:"),
      qq("金句：社交是充电还是耗电，全看你的电池型号。", "Quote: Socializing is charge or drain—depends on your battery model."),
      [o("E", "还行啊，要不要去第二摊续命", "Not bad—round two?", "社交回血", "Social heal"),
       o("I", "笑容已下线，灵魂正在打车回家", "Smile offline, soul ordering a ride", "电量告急", "Battery critical"),
       o("E", "可以再聊，但换成熟人小局", "Continue, but smaller familiar crew", "圈内续航", "Inner-circle stamina"),
       o("I", "到家第一件事：关机式沉默充电", "Home first task: silence charging mode", "洞穴回血", "Cave recharge")]),
    q(6, "SN", qq("旅游玄学 · S/N", "Trip Lore · S/N"),
      qq("规划旅行时，你更像？", "When planning a trip, you’re more like:"),
      qq("金句：地图负责现实，想象力负责浪漫。", "Quote: Maps handle reality; imagination handles romance."),
      [o("S", "交通/酒店/预算表先锁死", "Transport/hotel/budget locked first", "落地优先", "Ground first"),
       o("N", "先写情绪关键词：松弛/绝美/像电影", "Mood keywords first: soft/cinematic/wow", "氛围导演", "Vibe director"),
       o("S", "每站停留时长精确到分钟", "Dwell time per stop to the minute", "行程审计", "Itinerary audit"),
       o("N", "可能因为一家小店改整条路线", "One cute shop can reroute everything", "灵感改道", "Inspiration detour")]),
    q(7, "TF", qq("评价系统 · T/F", "Feedback OS · T/F"),
      qq("同事问“我这方案咋样”，你默认输出？", "Coworker: “How’s my plan?” Default output:"),
      qq("金句：真话要有用，温度要在线，缺一不可。", "Quote: Truth needs utility; care needs signal. Both required."),
      [o("T", "直接标红漏洞和优先级", "Mark holes and priorities in red", "效率手术刀", "Efficiency scalpel"),
       o("F", "先肯定努力，再温柔给建议", "Praise effort first, then soft suggestions", "情绪缓冲垫", "Emotion buffer"),
       o("T", "用数据说话，少讲感受", "Data first, feelings later", "理性播报", "Logic broadcast"),
       o("F", "先问他现在想听真话还是想被夸", "Ask: truth mode or hype mode?", "体贴开关", "Care switch")]),
    q(8, "JP", qq("DDL神学 · J/P", "Deadline Theology · J/P"),
      qq("截稿前 6 小时，你的精神状态？", "6 hours before deadline, your mental state:"),
      qq("金句：有人靠规划成神，有人靠肾上腺素成神。", "Quote: Some ascend by plans; some by adrenaline."),
      [o("J", "早做完了，现在在检查格式和备份", "Already done; checking format + backups", "稳定输出", "Stable output"),
       o("P", "灵感刚到，开始进入神之手速", "Inspiration just landed; godspeed typing", "爆发输出", "Burst mode"),
       o("J", "把任务拆成番茄钟，按表推进", "Split into pomodoros, march by the clock", "节奏机器", "Tempo machine"),
       o("P", "压力是催化剂，越临门越能写", "Pressure is catalyst; clutch writer activated", "绝境buff", "Clutch buff")]),
    q(9, "EI", qq("群聊政治 · E/I", "Groupchat Politics · E/I"),
      qq("百人工作群突然@所有人，你？", "100-person work chat @everyone. You:"),
      qq("金句：已读是态度，回复是立场，潜水是哲学。", "Quote: Read is attitude, reply is stance, mute is philosophy."),
      [o("E", "立刻回，顺便@相关人推进", "Reply instantly and @ the right people", "群聊发动机", "Chat engine"),
       o("I", "先已读，等风头过了再私聊", "Mark read; DM later when dust settles", "战术潜水", "Tactical dive"),
       o("E", "发个表情包缓和气氛再说话", "Send meme first, then talk", "气氛调节器", "Vibe regulator"),
       o("I", "把消息截图到备忘录，晚上再处理", "Screenshot to notes, process at night", "延迟批处理", "Batch later")]),
    q(10, "SN", qq("购物脑回路 · S/N", "Shopping Brain · S/N"),
      qq("你下单前最后一念通常是？", "Last thought before checkout:"),
      qq("金句：理性负责账户，感性负责快递盒里的快乐。", "Quote: Reason guards the account; feeling guards the unboxing joy."),
      [o("S", "对比参数、评价、退货率和到手价", "Compare specs, reviews, returns, final price", "精算师", "Actuary mode"),
       o("N", "想象它出现在我生活蒙太奇里的样子", "Imagine it in my life montage", "氛围消费", "Vibe spend"),
       o("S", "先看我有没有同类替代品", "Check if I already own a substitute", "库存管理", "Inventory check"),
       o("N", "买！这是新人格的装备", "Buy! Gear for my new persona", "人设补给", "Persona loot")]),
    q(11, "TF", qq("道歉语法 · T/F", "Apology Grammar · T/F"),
      qq("你不小心惹人不高兴，第一反应？", "You upset someone. First reaction:"),
      qq("金句：先修关系，再修逻辑，顺序反了会更炸。", "Quote: Repair the bond before the logic—or the bomb gets bigger."),
      [o("T", "说明事实：我本意不是那样", "Clarify facts: that wasn’t my intent", "澄清优先", "Clarify first"),
       o("F", "先认情绪：让你难受了，对不起", "Name the feeling: sorry I hurt you", "共情优先", "Empathy first"),
       o("T", "分析因果，避免下次再犯", "Map cause-effect; prevent next time", "复盘机器", "Postmortem bot"),
       o("F", "先递台阶和安慰，细节后补", "Offer comfort first, details later", "关系修复", "Relation patch")]),
    q(12, "JP", qq("行李哲学 · J/P", "Luggage Philosophy · J/P"),
      qq("出门前收拾行李，你是？", "Packing before leaving, you are:"),
      qq("金句：行李反映性格：有人带系统，有人带命运。", "Quote: Luggage reveals you: some pack systems, some pack fate."),
      [o("J", "前一晚清单打勾，充电器放指定袋", "Checklist night before; charger in assigned pouch", "封箱大师", "Seal master"),
       o("P", "临走前塞，到了再买也行", "Stuff last-minute; buy on site if needed", "现场补给", "Field resupply"),
       o("J", "按场景分类：通勤/运动/应急", "Sort by scenario: commute/gym/emergency", "模块化打包", "Modular pack"),
       o("P", "包里永远有神秘小物和半管牙膏", "Bag always has mystery items + half toothpaste", "混沌库存", "Chaos inventory")]),
    q(13, "EI", qq("陌生局开麦 · E/I", "Stranger Mic · E/I"),
      qq("朋友把你拉进一桌全是生人的局，你？", "Friend drops you into a table of strangers. You:"),
      qq("金句：社牛开麦，社恐开雷达，都是生存技能。", "Quote: Extroverts open mics; introverts open radar. Both are survival."),
      [o("E", "三分钟内找到话题发动机", "Find the conversation engine in 3 minutes", "破冰选手", "Icebreak pro"),
       o("I", "先当观察员，锁定安全座位", "Observe first, claim the safe seat", "场边雷达", "Sideline radar"),
       o("E", "主动自我介绍，顺便带节奏", "Self-intro and set the tempo", "主持附体", "Host possession"),
       o("I", "紧跟熟人，把社交外包给TA", "Stick to the friend; outsource socializing", "社交挂件", "Social pendant")]),
    q(14, "SN", qq("解释宇宙 · S/N", "Explain Universe · S/N"),
      qq("有人问“你最近在干嘛”，你更常？", "Someone asks “what have you been up to?” You usually:"),
      qq("金句：有人报流水账，有人播纪录片旁白。", "Quote: Some file a log; some narrate a documentary."),
      [o("S", "按时间线报：上班/加班/睡觉", "Report timeline: work/overtime/sleep", "流水账战士", "Log warrior"),
       o("N", "从“我在想人生方向”开始讲", "Start with “I’ve been thinking about life paths”", "宏观旁白", "Macro VO"),
       o("S", "给你看日历和已完成清单", "Show calendar + done list", "证据链", "Evidence chain"),
       o("N", "先讲一个隐喻：像在打地下城", "Lead with a metaphor: like grinding a dungeon", "比喻大师", "Metaphor mage")]),
    q(15, "TF", qq("选片大战 · T/F", "Movie War · T/F"),
      qq("约会选电影陷入僵局，你怎么破？", "Date night movie stalemate. You break it by:"),
      qq("金句：选片不是审美，是关系操作系统的小考。", "Quote: Picking a movie isn’t taste—it’s a tiny relationship exam."),
      [o("T", "评分/时长/类型矩阵投票", "Score/runtime/genre matrix vote", "决策表格", "Decision grid"),
       o("F", "你开心最重要，我陪看也行", "Your joy first; I’ll watch with you", "关系优先", "Relation first"),
       o("T", "轮流否决，剩最后两部再比", "Veto rounds until final two", "淘汰赛制", "Bracket system"),
       o("F", "先问你今天想哭还是想笑", "Ask: cry tonight or laugh?", "情绪匹配", "Mood match")]),
    q(16, "JP", qq("消息已读 · J/P", "Read Receipt · J/P"),
      qq("重要消息你通常怎么回？", "Important messages, you usually:"),
      qq("金句：秒回是礼貌，深思是品质，漂着是命运。", "Quote: Instant reply is manners; deep think is craft; floating is fate."),
      [o("J", "尽快回复，并设提醒跟进", "Reply fast + set follow-up reminder", "响应速度控", "Response speed"),
       o("P", "想清楚再回，可能已读很久", "Think first; may stay read for ages", "深思缓冲", "Deep buffer"),
       o("J", "先回确认收到，细节稍后补", "Ack first, details later", "回执选手", "ACK pro"),
       o("P", "灵感来了一次写长文，没来就漂着", "Write an essay when inspired, else float", "潮汐回复", "Tide reply")]),
    q(17, "EI", qq("精神状态播报 · E/I", "Status Broadcast · E/I"),
      qq("你“今天状态不错”时，更想？", "When you feel good today, you want to:"),
      qq("金句：好状态要么外放成派对，要么内耗成独处盛宴。", "Quote: Good mood either parties out or feasts alone."),
      [o("E", "约人出门，把好状态花掉", "Invite people out and spend the good mood", "状态外放", "Mood export"),
       o("I", "独自把想做的事先做爽", "Solo-do the things I’ve wanted", "状态内耗反向", "Solo feast"),
       o("E", "开语音/连麦分享今日高光", "Voice chat the day’s highlight reel", "高光直播", "Highlight stream"),
       o("I", "戴耳机散步，把世界静音", "Walk with headphones, mute the world", "安静暴富", "Quiet rich")]),
    q(18, "SN", qq("规则说明书 · S/N", "Rule Manual · S/N"),
      qq("新到一个陌生游戏/软件，你？", "New game/app. You:"),
      qq("金句：有人先读说明书，有人先把自己当说明书。", "Quote: Some read manuals; some become the tutorial by crashing first."),
      [o("S", "先看教程和设置页，摸清按钮", "Read tutorial + settings, map buttons", "说明书党", "Manual party"),
       o("N", "直接乱点，靠直觉闯关", "Mash around; intuition run", "野路子", "Wild path"),
       o("S", "搜“新手避坑”再动手", "Search beginner pitfalls first", "攻略启动", "Guide boot"),
       o("N", "先脑补它能变成什么神器", "Imagine what OP tool it could become", "潜力挖掘", "Potential dig")]),
    q(19, "TF", qq("分手建议 · T/F", "Breakup Counsel · T/F"),
      qq("朋友问“我该不该分”，你更像？", "Friend asks “should I break up?” You’re more:"),
      qq("金句：建议要准，立场要稳，情绪要接得住。", "Quote: Advice needs accuracy, stance, and emotional catch gloves."),
      [o("T", "列利弊表，看长期成本", "Pros/cons table; long-term cost", "理性顾问", "Logic advisor"),
       o("F", "先听完整故事，保护TA情绪", "Hear full story; protect feelings", "情绪保镖", "Emotion bodyguard"),
       o("T", "问：重复出现的问题是什么", "Ask: what’s the recurring bug?", "模式识别", "Pattern ID"),
       o("F", "你值得被好好对待，先站你", "You deserve care; I’m on your side", "站队型安慰", "Team-you comfort")]),
    q(20, "JP", qq("待办宇宙 · J/P", "Todo Universe · J/P"),
      qq("你的待办列表真实长相？", "Your real todo list looks like:"),
      qq("金句：清单是信仰，执行是修行，划掉是成佛。", "Quote: Lists are faith, doing is practice, checking off is nirvana."),
      [o("J", "分类、截止日期、优先级齐全", "Categories, due dates, priorities complete", "秩序圣殿", "Order temple"),
       o("P", "备忘录长文 + 随手便利贴漂浮", "Long notes + floating sticky notes", "星际碎片", "Space debris"),
       o("J", "做完一项立刻归档，看着就爽", "Archive on complete; dopamine clean", "清空癖", "Inbox zero cult"),
       o("P", "列表存在，执行看缘分和BGM", "List exists; execution needs fate + BGM", "BGM驱动", "BGM driven")]),
    q(21, "EI", qq("会议生存 · E/I", "Meeting Survival · E/I"),
      qq("开到一半的无聊会，你在干嘛？", "Halfway through a boring meeting, you are:"),
      qq("金句：会议要么推进世界，要么推进你的摸鱼技能。", "Quote: Meetings either move the world or level up your AFK skill."),
      [o("E", "找缝插话，把会聊成能推进的", "Find gaps and make it actionable", "会场救火", "Meeting firefighter"),
       o("I", "表面点头，内心开小差写笔记", "Nod outside, side-quest notes inside", "隐身办公", "Stealth work"),
       o("E", "会后拉人复盘，顺便社交一下", "Post-meeting huddle + light social", "会后局", "Afterparty work"),
       o("I", "摄像头关着，灵魂去了月球", "Cam off, soul on the moon", "月球出差", "Moon business trip")]),
    q(22, "SN", qq("梗图理解 · S/N", "Meme Parser · S/N"),
      qq("刷到抽象热梗，你第一反应？", "See an abstract viral meme. First reaction:"),
      qq("金句：懂梗是社交货币，不懂梗是考古现场。", "Quote: Getting memes is social currency; missing them is archaeology."),
      [o("S", "这是什么意思？出处在哪？", "What does it mean? Source?", "考据党", "Lore check"),
       o("N", "不管了，先笑，以后会自己懂", "Laugh first; understanding later", "氛围接入", "Vibe jack-in"),
       o("S", "保存后去搜百科式解释", "Save then search encyclopedia explainer", "释义引擎", "Definition engine"),
       o("N", "脑补成一套世界观继续二创", "Build a whole universe and remix it", "二创发动机", "Remix engine")]),
    q(23, "TF", qq("礼物选择 · T/F", "Gift Algorithm · T/F"),
      qq("给重要的人挑礼物，你更信？", "Picking a gift for someone important, you trust:"),
      qq("金句：礼物不是价格，是“我有没有把你放进心里”。", "Quote: Gifts aren’t price tags—they’re proof you kept someone in mind."),
      [o("T", "实用、耐用、可量化价值", "Useful, durable, measurable value", "功能派", "Utility school"),
       o("F", "对方提过的细节和小情绪", "Tiny details and feelings they mentioned", "记忆派", "Memory school"),
       o("T", "先做需求分析再下单", "Needs analysis then purchase", "需求文档", "Requirements doc"),
       o("F", "包装和送礼仪式感也很重要", "Wrapping + ritual matter a lot", "仪式感选手", "Ritual pro")]),
    q(24, "JP", qq("出门玄学 · J/P", "Leaving House Lore · J/P"),
      qq("约好 7 点见，你通常？", "Meetup at 7. You usually:"),
      qq("金句：守时是尊重，迟到是时空管理 debuff。", "Quote: On time is respect; late is a spacetime-management debuff."),
      [o("J", "6:40 到附近，卡点出现", "Arrive nearby 6:40, appear on time", "守时图腾", "Punctual totem"),
       o("P", "6:55 才找袜子，7:10 道歉上线", "Find socks at 6:55, apology online 7:10", "弹性时空", "Elastic spacetime"),
       o("J", "路线/停车/备用方案都想好", "Route/parking/backup planned", "预案控", "Contingency king"),
       o("P", "边走边决定吃什么穿什么", "Decide food/outfit while walking", "流动决策", "Flow decision")]),
    q(25, "EI", qq("朋友圈人设 · E/I", "Feed Persona · E/I"),
      qq("你发朋友圈的真实动机更接近？", "Real reason you post is closer to:"),
      qq("金句：有人发是为被看见，有人发是为把自己看见。", "Quote: Some post to be seen; some post to see themselves."),
      [o("E", "想被看见，顺便连结一下", "Want to be seen and connect", "公开播报", "Public broadcast"),
       o("I", "记录给自己，可见范围能多小多小", "Log for me; visibility as tiny as possible", "私人存档", "Private archive"),
       o("E", "有互动才完整，评论区也是局", "Interaction completes it; comments are a party", "评论区开趴", "Comment rave"),
       o("I", "写完就爽，点赞不点赞无所谓", "Writing is the reward; likes optional", "自给自足", "Self-sufficient")]),
    q(26, "SN", qq("未来想象 · S/N", "Future Cast · S/N"),
      qq("聊“五年后”，你更容易？", "Talking “in five years,” you more often:"),
      qq("金句：目标要落地，梦想要开地图。", "Quote: Goals need landing gear; dreams need an open map."),
      [o("S", "谈具体：城市、收入、技能栈", "Talk concrete: city, income, skill stack", "现实坐标", "Reality coords"),
       o("N", "谈方向：我想成为怎样的人", "Talk direction: who I want to become", "人设远景", "Persona horizon"),
       o("S", "先看现在资源能不能支撑", "Check if current resources can support it", "可行性审计", "Feasibility audit"),
       o("N", "先画一张很炫的平行宇宙草图", "Sketch a flashy parallel-universe draft", "宇宙草稿", "Universe draft")]),
    q(27, "TF", qq("争论现场 · T/F", "Argument Live · T/F"),
      qq("和亲近的人吵架时，你更在意？", "In a fight with someone close, you care more about:"),
      qq("金句：赢了道理输了人，这单生意不划算。", "Quote: Winning the point but losing the person is a bad trade."),
      [o("T", "谁对谁错、逻辑是否自洽", "Who’s right and if logic holds", "真理法庭", "Truth court"),
       o("F", "有没有被尊重、关系有没有裂", "Respect and whether the bond cracked", "关系体温", "Bond temperature"),
       o("T", "把问题定义清楚再谈感受", "Define the problem before feelings", "定义优先", "Define first"),
       o("F", "先降温，再谈事", "Cool down first, then talk issues", "灭火优先", "Fire first")]),
    q(28, "JP", qq("假期用法 · J/P", "Holiday OS · J/P"),
      qq("难得的三天假，你怎么用？", "Rare 3-day holiday. You use it to:"),
      qq("金句：假期不是空白，是你给生活打的补丁。", "Quote: Holidays aren’t blank space—they’re life’s patch notes."),
      [o("J", "安排主题日：学习日/清理日/社交日", "Theme days: study/clean/social", "假期工程", "Holiday engineering"),
       o("P", "睡到自然醒，再看世界抛什么任务", "Sleep in; see what world drops", "随缘假期", "Fate holiday"),
       o("J", "提前把杂事清完，假期专做想做的", "Clear chores first; holiday for wants", "前置清理", "Pre-clear"),
       o("P", "计划写满，真正执行看当天心情", "Full plan; execution depends on daily mood", "心情开关", "Mood switch")]),
    q(29, "EI", qq("能量来源 · E/I", "Energy Source · E/I"),
      qq("你回血最快的方式是？", "Fastest way you recharge:"),
      qq("金句：回血方式没错，硬装别人的充电器才会坏。", "Quote: Your charge method is fine—using someone else’s charger breaks you."),
      [o("E", "和对的人聊到兴奋", "Talk with the right people until lit", "对话充电", "Talk charge"),
       o("I", "独处、洗澡、发呆、不社交", "Alone, shower, zone out, no social", "独处回血", "Solo heal"),
       o("E", "去热闹但不需要深聊的场合", "Busy place without deep talk required", "人海泡脚", "Crowd soak"),
       o("I", "取消一切临时局，保护日历空白", "Cancel pop-up plans; protect blank calendar", "空白圣域", "Blank sanctuary")]),
    q(30, "SN", qq("工作汇报 · S/N", "Work Report · S/N"),
      qq("向领导汇报，你更习惯？", "Reporting to a boss, you prefer:"),
      qq("金句：结论是电梯，故事是风景，两者都要会开。", "Quote: Conclusions are elevators; stories are scenery—drive both."),
      [o("S", "先给结论、数据、下一步", "Conclusion, data, next steps first", "电梯演讲", "Elevator pitch"),
       o("N", "先讲背景故事和可能性地图", "Context story + possibility map first", "叙事开场", "Narrative open"),
       o("S", "用清单和截图证明进度", "Lists + screenshots as proof", "证据堆", "Evidence pile"),
       o("N", "用类比让对方秒懂全局", "Analogy so they get the whole map", "类比投射", "Analogy beam")]),
    q(31, "TF", qq("夸人系统 · T/F", "Praise System · T/F"),
      qq("你夸人时更像？", "When you praise someone, you’re more like:"),
      qq("金句：好的夸奖像精准投喂，不精确就只是噪声。", "Quote: Good praise is precise feeding; vague praise is just noise."),
      [o("T", "具体指出哪一步做得好", "Point to the exact step done well", "精确表扬", "Precision praise"),
       o("F", "先让对方感到被看见被喜欢", "Make them feel seen and liked first", "温度表扬", "Warm praise"),
       o("T", "少用形容词，多用事实", "Fewer adjectives, more facts", "事实勋章", "Fact medal"),
       o("F", "语气和表情都要送到", "Tone and face must deliver", "全感表扬", "Full-sense praise")]),
    q(32, "JP", qq("人生进度条 · J/P", "Life Loading Bar · J/P"),
      qq("面对“人生规划”，你真实态度？", "Real attitude toward “life planning”:"),
      qq("金句：主线让人安心，支线让人活着。", "Quote: Main quests calm you; side quests keep you alive."),
      [o("J", "有主线任务和里程碑才安心", "Need main quest + milestones to feel safe", "主线玩家", "Main-quest player"),
       o("P", "边走边开地图，支线也很香", "Open map while walking; side quests slap", "开放世界", "Open world"),
       o("J", "年度目标拆季拆月，定期复盘", "Year → quarter → month, review often", "复盘官", "Review officer"),
       o("P", "方向大概有，路径允许反复横跳", "Direction exists; path may zigzag", "弹性导航", "Elastic nav")]),
    q(33, "EI", qq("语音条人格 · E/I", "Voice-Note Persona · E/I"),
      qq("有人连发 12 条语音，你的真实反应？", "Someone drops 12 voice notes. Your real reaction:"),
      qq("金句：语音条是亲密，也是单向直播。", "Quote: Voice notes are intimacy—and a one-way livestream."),
      [o("E", "边听边回，像连麦一样热络", "Reply while listening, like a live call", "连麦体质", "Live-call body"),
       o("I", "先转文字，挑重点回，长语音缓缓", "Transcribe first, reply to key points later", "精简处理器", "Compact processor"),
       o("E", "直接打电话：说吧我在听", "Just call: talk, I’m listening", "语音升级", "Audio upgrade"),
       o("I", "收藏一下，等有电量再打开", "Save them; open when battery returns", "延时收听", "Delayed listen")]),
    q(34, "SN", qq("装修脑 · S/N", "Renovation Brain · S/N"),
      qq("房间要重装，你先想什么？", "Room remodel time. First thought:"),
      qq("金句：空间要么服务生活，要么服务幻想海报。", "Quote: Space either serves living—or your fantasy poster."),
      [o("S", "动线、收纳、插座数量先算清", "Flow, storage, outlet count first", "功能平面图", "Function plan"),
       o("N", "先定氛围关键词：赛博/原木/电影感", "Mood keywords first: cyber/wood/cinematic", "氛围样板间", "Vibe showroom"),
       o("S", "预算表和工期表必须先落地", "Budget + timeline must land first", "工程经理", "Build manager"),
       o("N", "先P一张理想房间再谈现实", "Photoshop dream room before reality", "愿景先行", "Vision first")]),
    q(35, "TF", qq("吐槽边界 · T/F", "Roast Boundary · T/F"),
      qq("朋友自黑求吐槽，你怎么玩？", "Friend self-roasts and asks you to pile on. You:"),
      qq("金句：吐槽是爱，越界是刀，刀要有刀鞘。", "Quote: Roasts are love; crossing lines is a knife—needs a sheath."),
      [o("T", "精准指出问题，顺带给改进路径", "Pinpoint the issue + improvement path", "锐评教练", "Sharp coach"),
       o("F", "先夸两句，再轻轻开玩笑", "Praise first, then soft joke", "安全吐槽", "Safe roast"),
       o("T", "开杠但保持事实准确", "Banter hard, keep facts accurate", "事实段子手", "Fact comic"),
       o("F", "看对方表情，随时刹车", "Watch their face; brake anytime", "情绪刹车", "Emotion brake")]),
    q(36, "JP", qq("日历信仰 · J/P", "Calendar Faith · J/P"),
      qq("你的日历 App 打开后更像？", "Your calendar app looks more like:"),
      qq("金句：时间管理不是压抑自由，是给自由开绿灯。", "Quote: Time management isn’t anti-freedom—it green-lights freedom."),
      [o("J", "色块密密麻麻，像地铁线路图", "Color blocks dense like a metro map", "时间建筑师", "Time architect"),
       o("P", "很多空白，真正安排靠当天灵感", "Lots of blank; real plans by daily spark", "空白艺术家", "Blank artist"),
       o("J", "提醒提前30/15/5分钟全开", "Reminders at 30/15/5 all on", "提醒狂魔", "Reminder cult"),
       o("P", "写了又改，改了又漂", "Write, edit, then drift again", "流动日历", "Flow calendar")]),
    q(37, "EI", qq("团建命运 · E/I", "Team-Building Fate · E/I"),
      qq("公司强制团建，你内心OS？", "Mandatory team building. Inner monologue:"),
      qq("金句：团建是社交副本，有人刷装备，有人刷沉默。", "Quote: Team building is a social dungeon—some farm gear, some farm silence."),
      [o("E", "冲！顺便认识新NPC", "Charge in and meet new NPCs", "副本冲锋", "Dungeon rush"),
       o("I", "能不能线上？我可以交作业代替", "Can it be online? I’ll submit homework instead", "远程遁术", "Remote escape"),
       o("E", "组织小游戏，把气氛带起来", "Host mini-games and lift the room", "气氛C位", "Vibe carry"),
       o("I", "找个角落当摄影师/记录员保命", "Hide as photographer/note-taker for survival", "职业隐身", "Job stealth")]),
    q(38, "SN", qq("新闻解读 · S/N", "News Decoder · S/N"),
      qq("刷到一条重磅新闻，你更先？", "Big news drops. You first:"),
      qq("金句：事实是地板，想象是天花板，房子要两边撑。", "Quote: Facts are the floor, imagination the ceiling—house needs both."),
      [o("S", "核对来源、数据、时间线", "Verify source, data, timeline", "事实安检", "Fact security"),
       o("N", "脑补后续剧情和行业连锁反应", "Imagine sequels and industry chain reactions", "推演导演", "Scenario director"),
       o("S", "先看官方通报和关键报道", "Official notes + key coverage first", "权威优先", "Authority first"),
       o("N", "先问：这对普通人生活意味着什么隐喻", "Ask: what metaphor does this hold for daily life?", "意义猎手", "Meaning hunter")]),
    q(39, "TF", qq("钱的态度 · T/F", "Money Mood · T/F"),
      qq("发了年终奖，你第一反应更像？", "Year-end bonus hits. First reaction closer to:"),
      qq("金句：钱要算清楚，心也要被善待。", "Quote: Count the money clearly—and treat the heart kindly too."),
      [o("T", "先还债/投资/分仓，再谈开心", "Debt/invest/allocate first, joy later", "资产调度", "Asset dispatch"),
       o("F", "先请重要的人吃顿好的", "Treat important people to a good meal first", "关系分红", "Bond reinvest"),
       o("T", "做张表：必要/提升/娱乐比例", "Make a sheet: need/upgrade/fun ratios", "比例控", "Ratio control"),
       o("F", "给自己买个仪式感小礼物", "Buy myself a small ritual gift", "自我犒劳", "Self treat")]),
    q(40, "JP", qq("学习副本 · J/P", "Study Dungeon · J/P"),
      qq("你要学一个新技能，开局方式是？", "Learning a new skill. Opening move:"),
      qq("金句：学习像打怪，有人练级表，有人边玩边掉装备。", "Quote: Learning is grinding—some use level charts, some loot while playing."),
      [o("J", "课程大纲+打卡表+每周复盘", "Syllabus + check-ins + weekly review", "系统升级", "System upgrade"),
       o("P", "先玩起来，卡了再搜", "Play first; search when stuck", "沉浸开荒", "Immerse start"),
       o("J", "先定可检验的小目标", "Set testable mini-goals first", "目标切片", "Goal slices"),
       o("P", "兴趣在就学，兴趣走了就换图", "Learn while interested; switch maps when it fades", "兴趣导航", "Interest nav")]),
    q(41, "EI", qq("表达欲开关 · E/I", "Expression Switch · E/I"),
      qq("你刚想通一件大事，最想？", "You just figured out something big. You most want to:"),
      qq("金句：想通是内功，说出来是外放，时机要选。", "Quote: Insight is internal power; saying it is export—timing matters."),
      [o("E", "马上找人讲，越讲越清晰", "Tell someone now; clarity grows by talking", "外放整理", "Talk-to-sort"),
       o("I", "先写进笔记，自己消化完再说", "Write notes first; digest before speaking", "内功沉淀", "Inner settle"),
       o("E", "发动态/群里抛出来讨论", "Post or drop it in a group for debate", "公开碰撞", "Public collide"),
       o("I", "只告诉极少数信任的人", "Tell only a tiny trusted circle", "精选听众", "Select audience")]),
    q(42, "SN", qq("回忆滤镜 · S/N", "Memory Filter · S/N"),
      qq("翻旧照片时，你更常想起？", "Looking at old photos, you more often recall:"),
      qq("金句：细节让人落地，意义让人起飞。", "Quote: Details ground you; meaning lets you take off."),
      [o("S", "那天穿了什么、吃了什么、几点出发", "Clothes, food, departure time that day", "细节回放", "Detail replay"),
       o("N", "那阶段我是谁、想成为谁", "Who I was then, who I wanted to become", "人设考古", "Persona archaeology"),
       o("S", "地点、路线、物价这些硬信息", "Place, route, prices—hard facts", "事实存档", "Fact archive"),
       o("N", "一种说不清的氛围和命运感", "An ineffable vibe and sense of fate", "氛围残影", "Vibe afterimage")]),
    q(43, "TF", qq("规则冲突 · T/F", "Rule Clash · T/F"),
      qq("团队规则伤到某个人，你更倾向？", "A team rule hurts someone. You lean to:"),
      qq("金句：规则保护大多数，温度保护具体的人。", "Quote: Rules protect the many; warmth protects the specific person."),
      [o("T", "规则面前尽量一视同仁", "Keep the rule as even as possible", "公平标尺", "Fair ruler"),
       o("F", "先照顾当事人感受再谈规则", "Care for the person first, then the rule", "人本优先", "Human first"),
       o("T", "评估例外会不会破坏系统", "Check if exceptions break the system", "系统审计", "System audit"),
       o("F", "找一个不伤人的折中方案", "Find a compromise that doesn’t wound", "柔性折中", "Soft middle")]),
    q(44, "JP", qq("突发改约 · J/P", "Sudden Reschedule · J/P"),
      qq("约好的局突然取消，你？", "A planned hangout is suddenly canceled. You:"),
      qq("金句：计划被改写时，看你是修路人还是冲浪人。", "Quote: When plans rewrite, you’re either a road-fixer or a surfer."),
      [o("J", "立刻改期并同步所有人", "Reschedule instantly and sync everyone", "改期机器", "Reschedule bot"),
       o("P", "正好，今天变自由日", "Perfect—today becomes Free Day", "意外礼物", "Surprise gift"),
       o("J", "把空出来的时间填回待办", "Fill freed time back into todos", "时间回收", "Time reclaim"),
       o("P", "走到哪算哪，开启随机事件", "Go wherever; trigger random events", "随机传送", "Random teleport")]),
    q(45, "EI", qq("沉默舒适度 · E/I", "Silence Comfort · E/I"),
      qq("和不太熟的人一起沉默 30 秒，你？", "30 seconds of silence with someone new. You:"),
      qq("金句：沉默不是失败，硬聊才可能翻车。", "Quote: Silence isn’t failure—forced chat is the real crash risk."),
      [o("E", "立刻找话题填空白", "Fill the blank with a topic ASAP", "空白恐惧症", "Blank-phobia"),
       o("I", "安静也行，不尴尬是我的技能", "Quiet is fine; unbothered is my skill", "静默坦克", "Silence tank"),
       o("E", "用玩笑把气氛拉回来", "Joke the vibe back", "气氛钩子", "Vibe hook"),
       o("I", "看手机缓冲，等自然话题掉落", "Phone buffer until a natural topic drops", "等待刷新", "Wait refresh")]),
    q(46, "SN", qq("做饭哲学 · S/N", "Cooking Philosophy · S/N"),
      qq("你做饭时更像？", "When cooking, you’re more like:"),
      qq("金句：菜谱是地图，味觉是指南针。", "Quote: Recipes are maps; taste is the compass."),
      [o("S", "严格按克数和步骤走", "Follow grams and steps strictly", "实验员", "Lab cook"),
       o("N", "看菜下锅，灵感调味", "Cook by vibe; season by inspiration", "灵感主厨", "Inspiration chef"),
       o("S", "先备齐所有材料再开火", "Mise en place everything before heat", "前置准备", "Prep first"),
       o("N", "边做边改成“今日限定菜”", "Remix into today’s limited special", "限定研发", "Limited R&D")]),
    q(47, "TF", qq("被夸之后 · T/F", "After Praise · T/F"),
      qq("被当众夸奖时，你内在更像？", "Publicly praised, your inner self is more:"),
      qq("金句：接受夸奖也是一种能力，别只会拆自己。", "Quote: Receiving praise is a skill—stop only dismantling yourself."),
      [o("T", "分析：这次好在哪里，能否复现", "Analyze: what worked and can it repeat", "复盘接收", "Review receive"),
       o("F", "心里暖一下，也有点不好意思", "Feel warm, a bit shy", "害羞充电", "Shy charge"),
       o("T", "把功劳拆成方法，避免神化", "Break credit into methods, avoid myth", "去魅工程师", "Demystify eng"),
       o("F", "马上回夸对方，关系升温", "Praise back immediately; warm the bond", "互夸回路", "Praise loop")]),
    q(48, "JP", qq("睡前仪式 · J/P", "Bedtime Ritual · J/P"),
      qq("临睡前最后 20 分钟，你通常？", "Last 20 minutes before sleep, you usually:"),
      qq("金句：睡眠是明天的启动项，也是今天的关机键。", "Quote: Sleep is tomorrow’s boot item—and today’s shutdown key."),
      [o("J", "设闹钟、查明日日程、断网入睡", "Set alarms, check tomorrow, go offline", "关机流程", "Shutdown flow"),
       o("P", "再刷一会儿，看到哪算哪", "Scroll a bit more; stop wherever", "漂移入睡", "Drift sleep"),
       o("J", "洗漱护肤按固定顺序完成", "Fixed wash/skincare sequence", "仪式闭环", "Ritual loop"),
       o("P", "突然想起来还有件事，半梦半做", "Suddenly remember a task; half-dream do it", "夜半支线", "Midnight side quest")]),
]


def dump(name, value):
    return f"const {name} = {json.dumps(value, ensure_ascii=False, indent=2)};\n"


def type_entry(code, name_zh, name_en, english, energy_zh, energy_en, s_zh, s_en, t_zh, t_en, p_zh, p_en,
               analysis_zh, analysis_en, snark_zh, snark_en, fantasy_zh, fantasy_en, animal_zh, animal_en, emoji,
               traits_zh, traits_en, strengths_zh, strengths_en, watch_zh, watch_en, tip_zh, tip_en, slogan_zh, slogan_en):
    return {
        "code": code,
        "name": {"zh": name_zh, "en": name_en},
        "english": english,
        "energy": {"zh": energy_zh, "en": energy_en},
        "sensing": {"zh": s_zh, "en": s_en},
        "thinking": {"zh": t_zh, "en": t_en},
        "planning": {"zh": p_zh, "en": p_en},
        "analysis": {"zh": analysis_zh, "en": analysis_en},
        "snark": {"zh": snark_zh, "en": snark_en},
        "fantasy": {"zh": fantasy_zh, "en": fantasy_en},
        "animal": {"zh": animal_zh, "en": animal_en},
        "emoji": emoji,
        "traits": {"zh": traits_zh, "en": traits_en},
        "strengths": {"zh": strengths_zh, "en": strengths_en},
        "watchouts": {"zh": watch_zh, "en": watch_en},
        "growth": {"zh": tip_zh, "en": tip_en},
        "slogan": {"zh": slogan_zh, "en": slogan_en},
    }


TYPES = {
    "INTJ": type_entry("INTJ", "战略架构师", "Strategy Architect", "Mastermind", "内倾直觉", "Introverted Intuition", "直觉型 (N)", "Intuitive (N)", "思维型 (T)", "Thinking (T)", "判断型 (J)", "Judging (J)",
        "你擅长把混乱收成主线，用长期视角做选择。独立、高效，对低质量重复几乎零耐心。", "You compress chaos into a mainline and choose with long horizons. Independent, efficient, allergic to low-quality repetition.",
        "嘴上说随便，内心已经写完三种结局和风险附录。", "You say “whatever,” while finishing three endings and a risk appendix.",
        "时空蓝图法师", "Timeline Blueprint Mage", "猫头鹰策划官", "Owl Strategist", "🔮",
        ["长远规划", "系统思维", "独立决策"], ["long-range planning", "systems thinking", "independent decisions"],
        ["战略拆解", "高效取舍", "抗干扰"], ["strategy breakdown", "efficient tradeoffs", "noise resistance"],
        ["对情绪信号不敏感", "容易显得冷"], ["miss emotional signals", "can read as cold"],
        "把“为什么”讲给人听，合作会顺很多。", "Say the why out loud—collaboration gets smoother.",
        "我不是冷，我只是在加载全局。", "Not cold—just loading the full map."),
    "INTP": type_entry("INTP", "逻辑探索者", "Logic Explorer", "Logician", "内倾直觉", "Introverted Intuition", "直觉型 (N)", "Intuitive (N)", "思维型 (T)", "Thinking (T)", "知觉型 (P)", "Perceiving (P)",
        "你靠好奇心驱动，喜欢拆原理、挑战假设。自由思考是氧气，落地时需要一点外部结构。", "Curiosity-driven; you dismantle principles and challenge assumptions. Free thought is oxygen; shipping needs structure.",
        "思考链路：展开→卡住→再展开→忘吃饭→突然顿悟。", "Thought chain: expand → freeze → expand → forget lunch → enlightenment.",
        "原理拆解炼金师", "Principle Alchemy Scholar", "狐狸实验员", "Fox Labmate", "🧪",
        ["好奇拆解", "概念灵活", "独立思考"], ["curious deconstruction", "flexible concepts", "independent thought"],
        ["洞察本质", "创新假设", "冷静分析"], ["essence insight", "novel hypotheses", "calm analysis"],
        ["拖延落地", "社交电量不稳"], ["shipping delay", "uneven social battery"],
        "给灵感设一个最小可交付版本。", "Give inspiration a minimum shippable version.",
        "我想通了，但还没写进文档。", "I got it—just not in the doc yet."),
    "ENTJ": type_entry("ENTJ", "决断指挥官", "Decisive Commander", "Commander", "外倾思维", "Extraverted Thinking", "直觉型 (N)", "Intuitive (N)", "思维型 (T)", "Thinking (T)", "判断型 (J)", "Judging (J)",
        "你天然会定目标、分资源、推执行。高标准不是压力，是默认设置。", "You set goals, allocate resources, and push execution by default. High standards are factory settings.",
        "你的待办列表比别人的人生规划还像正式文件。", "Your todo list looks more official than most life plans.",
        "远征军团统帅", "Expedition Legion Marshal", "雄狮项目经理", "Lion PM", "⚡",
        ["目标导向", "组织推动", "高压执行"], ["goal-driven", "org push", "high-pressure execution"],
        ["决策速度", "资源调度", "结果负责"], ["decision speed", "resource allocation", "result ownership"],
        ["忽略节奏差异", "表达过硬"], ["miss pace differences", "over-hard delivery"],
        "在推进度前先同步人的状态。", "Sync people’s state before pushing pace.",
        "目标不是梦想，是排期。", "A goal isn’t a dream—it’s a schedule."),
    "ENTP": type_entry("ENTP", "灵感辩论家", "Idea Debater", "Debater", "外倾直觉", "Extraverted Intuition", "直觉型 (N)", "Intuitive (N)", "思维型 (T)", "Thinking (T)", "知觉型 (P)", "Perceiving (P)",
        "你点子密度高，擅长在对立里挖新路。变化是燃料，无聊是终极BOSS。", "High idea density; you dig new paths from opposition. Change is fuel; boredom is final boss.",
        "你不是抬杠，你是在给现实做压力测试。", "Not arguing—stress-testing reality.",
        "混沌创意发明家", "Chaos Idea Inventor", "灵狐段子手", "Spirit Fox Comic", "🎨",
        ["脑暴连发", "辩论快感", "机会嗅觉"], ["brainstorm bursts", "debate joy", "opportunity radar"],
        ["创意连接", "快速试错", "现场应变"], ["idea linking", "fast experiments", "live adaptability"],
        ["项目过多", "收尾不稳"], ["too many projects", "weak closing"],
        "每个点子配一个“完成定义”。", "Give every idea a definition of done.",
        "我反对，是为了更好的版本。", "I object for a better version."),
    "INFJ": type_entry("INFJ", "洞察引路人", "Insight Guide", "Advocate", "内倾直觉", "Introverted Intuition", "直觉型 (N)", "Intuitive (N)", "情感型 (F)", "Feeling (F)", "判断型 (J)", "Judging (J)",
        "你能听见没说出口的部分，并把它们织成方向。深度连接比热闹更重要。", "You hear the unsaid and weave it into direction. Depth beats noise.",
        "表面温柔，内心已经把剧情推到终章还写了旁白。", "Soft face, internal director’s cut already at the finale.",
        "星轨预言顾问", "Star-Path Oracle Advisor", "月鹿倾听者", "Moon Deer Listener", "🌙",
        ["深度共情", "意义导向", "远见"], ["deep empathy", "meaning-led", "foresight"],
        ["洞察人心", "长期陪伴", "价值导航"], ["people insight", "long-term support", "value navigation"],
        ["过度内耗", "边界模糊"], ["over-rumination", "blurry boundaries"],
        "把感受说出口，也给自己留白。", "Say feelings out loud—and leave white space for yourself.",
        "我看见了，所以我在意。", "I see it, so I care."),
    "INFP": type_entry("INFP", "理想诗人", "Ideal Poet", "Mediator", "内倾情感", "Introverted Feeling", "直觉型 (N)", "Intuitive (N)", "情感型 (F)", "Feeling (F)", "知觉型 (P)", "Perceiving (P)",
        "你以价值感导航，对真诚极度敏感。世界粗糙时，你会用想象给它包一层软壳。", "You navigate by values and are allergic to fake. When the world is rough, imagination becomes soft armor.",
        "外表云淡风轻，收藏夹里全是没写完的人生剧本。", "Calm exterior; drafts folder full of unfinished life scripts.",
        "梦境叙事旅人", "Dream Narrative Wanderer", "猫咪诗人", "Poet Cat", "🌸",
        ["价值敏感", "想象丰富", "温和坚持"], ["value-sensitive", "rich imagination", "gentle persistence"],
        ["真诚表达", "创意共情", "独特审美"], ["sincere expression", "creative empathy", "unique taste"],
        ["逃避冲突", "行动犹豫"], ["conflict avoidance", "action hesitation"],
        "把理想拆成今天能做的一小步。", "Split ideals into one small step today.",
        "世界可以吵，我的真心不降噪。", "The world can be loud; my sincerity stays unmuted."),
    "ENFJ": type_entry("ENFJ", "热血组织者", "Warm Organizer", "Protagonist", "外倾情感", "Extraverted Feeling", "直觉型 (N)", "Intuitive (N)", "情感型 (F)", "Feeling (F)", "判断型 (J)", "Judging (J)",
        "你天然会把人聚起来，给方向也给温度。责任心强，有时会忘了给自己留电量。", "You gather people, give direction and warmth. High responsibility; sometimes forget your own battery.",
        "你是人形群公告：关心所有人，唯独漏掉自己。", "Human group announcement: care for all, skip self.",
        "同盟篝火主持", "Alliance Bonfire Host", "金毛啦啦队", "Golden Retriever MC", "🔥",
        ["带动氛围", "责任担当", "人际敏感"], ["vibe leading", "responsibility", "people sensitivity"],
        ["激励他人", "协调冲突", "组织成长"], ["motivate others", "mediate conflict", "grow groups"],
        ["过度付出", "自我忽略"], ["overgiving", "self-neglect"],
        "把“我也需要休息”写进日程。", "Put “I also need rest” on the calendar.",
        "大家先来，我垫后——但我也要充电。", "You first, I cover—then I recharge too."),
    "ENFP": type_entry("ENFP", "火花冒险家", "Spark Adventurer", "Campaigner", "外倾直觉", "Extraverted Intuition", "直觉型 (N)", "Intuitive (N)", "情感型 (F)", "Feeling (F)", "知觉型 (P)", "Perceiving (P)",
        "你是走动的灵感弹幕，连接人与点子的速度很快。热情是超能力，也需要落地锚点。", "A walking inspiration barrage; you connect people and ideas fast. Passion is a superpower that needs anchors.",
        "同时开了 12 个兴趣标签页，还都觉得自己会回去看。", "12 interest tabs open, all convinced you’ll return.",
        "彩虹传送门导游", "Rainbow Portal Guide", "鹦鹉派对官", "Party Parrot", "✨",
        ["热情连接", "创意发散", "即兴表达"], ["warm connection", "idea divergence", "improv expression"],
        ["点燃气氛", "跨界串联", "快速共情"], ["spark rooms", "cross-link people", "fast empathy"],
        ["专注易散", "承诺过载"], ["focus scatter", "promise overload"],
        "兴趣可以多，完成要排队。", "Many interests are fine—completion needs a queue.",
        "我不是三分钟热度，我是多线程人生。", "Not short attention—multithreaded life."),
    "ISTJ": type_entry("ISTJ", "可靠执行官", "Reliable Executor", "Logistician", "内倾实感", "Introverted Sensing", "实感型 (S)", "Sensing (S)", "思维型 (T)", "Thinking (T)", "判断型 (J)", "Judging (J)",
        "你靠规则、记忆和流程把事情做成。承诺很重，靠谱是你的默认皮肤。", "Rules, memory, and process make things real. Promises are heavy; reliability is default skin.",
        "别人靠灵感，你靠备份、清单和准时到场。", "Others run on inspiration; you run on backups, lists, and on-time arrival.",
        "古城档案守护者", "Archive Guardian", "獾式审计员", "Badger Auditor", "📋",
        ["稳定执行", "细节记忆", "责任清晰"], ["stable execution", "detail memory", "clear duty"],
        ["可靠交付", "流程优化", "风险预防"], ["reliable delivery", "process polish", "risk prevention"],
        ["变化适应慢", "表达偏硬"], ["slow change adapt", "stiff expression"],
        "允许 10% 的弹性，世界不会塌。", "Allow 10% flex—the world won’t collapse.",
        "我说到，就会做到。", "If I say it, I do it."),
    "ISFJ": type_entry("ISFJ", "温柔守护者", "Gentle Guardian", "Defender", "内倾实感", "Introverted Sensing", "实感型 (S)", "Sensing (S)", "情感型 (F)", "Feeling (F)", "判断型 (J)", "Judging (J)",
        "你记得别人容易忽略的细节，用稳定照顾维持秩序。安静，但关键度很高。", "You remember details others miss and keep order through steady care. Quiet, high loyalty.",
        "你是团队的隐形后勤，直到你请假大家才发现世界塌了。", "Invisible logistics—until you take leave and the world collapses.",
        "暖灯药剂师", "Warm-Lamp Apothecary", "企鹅护理员", "Penguin Care", "🛡️",
        ["细心照顾", "忠诚稳定", "默默支持"], ["careful support", "loyal stability", "quiet backing"],
        ["关系维护", "实操靠谱", "体贴入微"], ["bond maintenance", "practical reliability", "micro care"],
        ["不擅长拒绝", "情绪积压"], ["hard to refuse", "emotion backlog"],
        "学会说“这次我帮不到”，也是爱。", "Saying “I can’t this time” is also love.",
        "我记得你提过的小事。", "I remember the small thing you mentioned."),
    "ESTJ": type_entry("ESTJ", "现场指挥官", "Field Commander", "Executive", "外倾思维", "Extraverted Thinking", "实感型 (S)", "Sensing (S)", "思维型 (T)", "Thinking (T)", "判断型 (J)", "Judging (J)",
        "你擅长把目标变成可执行动作，并推动大家按节奏完成。结果导向，效率优先。", "You turn goals into executable moves and push the tempo. Results first, efficiency always.",
        "你的人生BGM是进度条提示音。", "Your life BGM is a progress-bar ping.",
        "城邦秩序执政官", "City Order Consul", "鹰式督导", "Eagle Supervisor", "🏛️",
        ["现场推动", "标准清晰", "结果负责"], ["field drive", "clear standards", "result ownership"],
        ["组织落地", "效率提升", "秩序建立"], ["org landing", "efficiency lift", "order building"],
        ["弹性不足", "听感偏强势"], ["low flexibility", "can sound forceful"],
        "在发指令前先问一句“你卡在哪”。", "Before orders, ask “where are you stuck?”",
        "别聊风花雪月，先把进度对齐。", "Skip poetry—align the progress first."),
    "ESFJ": type_entry("ESFJ", "氛围主理人", "Atmosphere Host", "Consul", "外倾情感", "Extraverted Feeling", "实感型 (S)", "Sensing (S)", "情感型 (F)", "Feeling (F)", "判断型 (J)", "Judging (J)",
        "你对关系场极其敏感，会主动把局盘热、把人照顾好。和谐是你的KPI。", "Highly sensitive to relational fields; you warm rooms and care for people. Harmony is your KPI.",
        "聚餐座位表在你脑子里比公司架构图还清楚。", "Seating charts live clearer in your head than org charts.",
        "节日宴席大总管", "Festival Banquet Steward", "柯基接待官", "Corgi Concierge", "🎀",
        ["关系经营", "服务意识", "现场温度"], ["relationship ops", "service sense", "room warmth"],
        ["凝聚力", "细节招待", "冲突缓和"], ["cohesion", "detail hospitality", "conflict softener"],
        ["过度在意评价", "难做恶人"], ["overcare about opinions", "hard to play bad cop"],
        "和谐很重要，但你的边界也是和谐的一部分。", "Harmony matters—and your boundary is part of it.",
        "来，我给你留了最好的位置。", "Come on—I saved you the best seat."),
    "ISTP": type_entry("ISTP", "冷静技师", "Cool Technician", "Virtuoso", "内倾思维", "Introverted Thinking", "实感型 (S)", "Sensing (S)", "思维型 (T)", "Thinking (T)", "知觉型 (P)", "Perceiving (P)",
        "你用动手和观察理解世界，危机时反而更稳。少说多做，自由空间是刚需。", "You learn by doing and observing; calmer in crisis. Less talk, more craft; freedom is non-negotiable.",
        "表面上在发呆，其实已经把故障点定位到第三个螺丝。", "Looks zoned out; already pinned the fault to screw #3.",
        "机械灵巧侠", "Mech Dexterity Ranger", "猫科维修工", "Cat Mechanic", "🛠️",
        ["动手实操", "冷静拆解", "自由节奏"], ["hands-on craft", "calm teardown", "free tempo"],
        ["故障定位", "临场反应", "工具思维"], ["fault locating", "live response", "tool thinking"],
        ["表达偏少", "长期规划弱"], ["low verbal share", "weaker long plans"],
        "偶尔把你的判断说出来，别人会更信你。", "Say your judgment out loud sometimes—people trust you more.",
        "别吵，让我听听机器怎么说。", "Quiet—let me hear what the machine says."),
    "ISFP": type_entry("ISFP", "感官艺术家", "Sensory Artist", "Adventurer", "内倾情感", "Introverted Feeling", "实感型 (S)", "Sensing (S)", "情感型 (F)", "Feeling (F)", "知觉型 (P)", "Perceiving (P)",
        "你通过美、节奏和当下体验认识自己。不喜欢被框住，真诚比表演重要。", "You know yourself through beauty, rhythm, and present experience. Hate cages; sincerity > performance.",
        "别人卷KPI，你在卷日落角度和耳机歌单。", "Others grind KPIs; you grind sunset angles and playlists.",
        "风色采集成长者", "Wind-Color Forager", "小熊猫美学官", "Red Panda Aesthete", "🎧",
        ["审美敏锐", "当下感受", "温和自由"], ["aesthetic radar", "present feel", "gentle freedom"],
        ["风格表达", "氛围营造", "真诚陪伴"], ["style expression", "vibe crafting", "sincere company"],
        ["回避冲突", "规划不稳定"], ["avoid conflict", "unstable planning"],
        "把喜欢的事做成可重复的小习惯。", "Turn what you love into small repeatable habits.",
        "这刻好看，就值得认真过。", "If this moment is beautiful, it’s worth living fully."),
    "ESTP": type_entry("ESTP", "现场玩家", "Field Player", "Entrepreneur", "外倾实感", "Extraverted Sensing", "实感型 (S)", "Sensing (S)", "思维型 (T)", "Thinking (T)", "知觉型 (P)", "Perceiving (P)",
        "你反应快、敢试错，擅长把机会从现场里捞出来。行动优先，理论后补。", "Fast reactions, bold experiments; you scoop opportunity from the field. Action first, theory later.",
        "计划还在加载，人已经到现场了。", "Plan still loading; you’re already on site.",
        "风暴特技领航员", "Storm Stunt Navigator", "猎豹冲锋员", "Cheetah Striker", "🏎️",
        ["行动派", "机会嗅觉", "临场博弈"], ["action bias", "opportunity nose", "live game sense"],
        ["快速成交", "危机处理", "现场领导"], ["fast close", "crisis handling", "on-site lead"],
        ["耐心不足", "细节遗漏"], ["low patience", "detail misses"],
        "冲之前花 60 秒看风险清单。", "Spend 60 seconds on a risk list before charging.",
        "别讨论了，先试一枪。", "Stop debating—fire a test shot."),
    "ESFP": type_entry("ESFP", "现场明星", "Live Star", "Entertainer", "外倾实感", "Extraverted Sensing", "实感型 (S)", "Sensing (S)", "情感型 (F)", "Feeling (F)", "知觉型 (P)", "Perceiving (P)",
        "你把当下过成舞台，感染力强，擅长让人放松。快乐是策略，也是天赋。", "You turn the present into a stage; strong presence, great at easing people. Joy is both strategy and gift.",
        "你一进门，局的音量自动上调两格。", "You enter; the room volume auto-raises two notches.",
        "星光派对领唱", "Starlight Party Lead", "海豚气氛组", "Dolphin Vibe Crew", "🎤",
        ["现场魅力", "快乐传导", "即兴互动"], ["live charm", "joy transmission", "improv interaction"],
        ["带动情绪", "社交润滑", "体验设计"], ["mood lifting", "social lube", "experience design"],
        ["长期规划弱", "易被即时刺激带走"], ["weak long plans", "pulled by instant stimuli"],
        "给快乐加一个明天也能复用的结构。", "Add a structure so joy can reuse tomorrow.",
        "人生短，先把这局玩好看。", "Life’s short—make this round look good."),
}

CAREERS = {
  "INTJ": [{"zh":"产品战略 / 系统架构","en":"Product strategy / systems architecture"},{"zh":"研究分析 / 投资研究","en":"Research analysis / investment research"},{"zh":"复杂项目负责人","en":"Complex program lead"}],
  "INTP": [{"zh":"研发工程 / 算法","en":"R&D engineering / algorithms"},{"zh":"数据分析 / 科学探索","en":"Data analysis / scientific exploration"},{"zh":"独立创作者（硬核向）","en":"Independent creator (deep-tech)"}],
  "ENTJ": [{"zh":"管理培训 / 业务负责人","en":"Management track / business owner"},{"zh":"创业操盘 / 咨询","en":"Startup operator / consulting"},{"zh":"运营增长负责人","en":"Growth operations lead"}],
  "ENTP": [{"zh":"创新业务 / BD","en":"New business / BD"},{"zh":"内容策略 / 产品探索","en":"Content strategy / product discovery"},{"zh":"媒体与辩论型表达","en":"Media & debate-driven roles"}],
  "INFJ": [{"zh":"咨询辅导 / 用户研究","en":"Coaching / user research"},{"zh":"品牌叙事 / 教育设计","en":"Brand narrative / learning design"},{"zh":"非营利与社会创新","en":"Nonprofit & social innovation"}],
  "INFP": [{"zh":"写作编辑 / 设计","en":"Writing/editing / design"},{"zh":"心理相关支持工作","en":"Psychology-adjacent support"},{"zh":"独立艺术与内容","en":"Indie art & content"}],
  "ENFJ": [{"zh":"团队管理 / HRBP","en":"People management / HRBP"},{"zh":"教师培训 / 社区运营","en":"Teaching/training / community ops"},{"zh":"客户成功","en":"Customer success"}],
  "ENFP": [{"zh":"市场创意 / 品牌活动","en":"Marketing creative / brand events"},{"zh":"内容与播客主持","en":"Content & podcast hosting"},{"zh":"跨界项目连接者","en":"Cross-team connector"}],
  "ISTJ": [{"zh":"财务审计 / 质量管控","en":"Finance audit / quality control"},{"zh":"运营流程 / 法务合规","en":"Ops process / legal compliance"},{"zh":"项目管理执行","en":"Project execution"}],
  "ISFJ": [{"zh":"医疗护理 / 行政支持","en":"Healthcare / admin support"},{"zh":"客户服务管理","en":"Customer service management"},{"zh":"教育教务","en":"Academic administration"}],
  "ESTJ": [{"zh":"运营管理 / 供应链","en":"Operations / supply chain"},{"zh":"销售管理 / 现场督导","en":"Sales management / field supervision"},{"zh":"公共事务执行","en":"Public affairs execution"}],
  "ESFJ": [{"zh":"活动策划 / 接待管理","en":"Event planning / hospitality"},{"zh":"社群与会员运营","en":"Community & membership ops"},{"zh":"医疗与教育服务窗口","en":"Service-facing education/health roles"}],
  "ISTP": [{"zh":"工程技术 / 运维","en":"Engineering / ops tech"},{"zh":"应急处理 / 技工专家","en":"Incident response / craft specialist"},{"zh":"产品硬件测试","en":"Hardware product testing"}],
  "ISFP": [{"zh":"视觉设计 / 摄影","en":"Visual design / photography"},{"zh":"手作与体验设计","en":"Craft & experience design"},{"zh":"生活方式内容","en":"Lifestyle content"}],
  "ESTP": [{"zh":"销售前线 / 商务谈判","en":"Frontline sales / negotiation"},{"zh":"体育与现场活动","en":"Sports & live events"},{"zh":"创业实操与拓客","en":"Hands-on startup hustle"}],
  "ESFP": [{"zh":"表演主持 / 直播","en":"Performance / hosting / livestream"},{"zh":"旅游与体验零售","en":"Travel & experiential retail"},{"zh":"公关与品牌现场","en":"PR & on-site brand work"}],
}

MATCHES = {
  "INTJ": {"best": ["ENFP", "ENTP", "INFJ"], "conflict": ["ESFP", "ISFP"]},
  "INTP": {"best": ["ENTJ", "ENFJ", "INTJ"], "conflict": ["ESFJ", "ISFJ"]},
  "ENTJ": {"best": ["INTP", "INFP", "ENTP"], "conflict": ["ISFP", "ESFP"]},
  "ENTP": {"best": ["INFJ", "INTJ", "ENFJ"], "conflict": ["ISFJ", "ISTJ"]},
  "INFJ": {"best": ["ENFP", "ENTP", "INTJ"], "conflict": ["ESTP", "ESFP"]},
  "INFP": {"best": ["ENFJ", "ENTJ", "INFJ"], "conflict": ["ESTJ", "ESFJ"]},
  "ENFJ": {"best": ["INFP", "ISFP", "INFJ"], "conflict": ["ISTP", "INTP"]},
  "ENFP": {"best": ["INFJ", "INTJ", "ENFJ"], "conflict": ["ISTJ", "ESTJ"]},
  "ISTJ": {"best": ["ESFJ", "ESTJ", "INTJ"], "conflict": ["ENFP", "ENTP"]},
  "ISFJ": {"best": ["ESFP", "ESTJ", "ISFP"], "conflict": ["ENTP", "ENTJ"]},
  "ESTJ": {"best": ["ISFJ", "ISTJ", "ESFJ"], "conflict": ["INFP", "ENFP"]},
  "ESFJ": {"best": ["ISFJ", "ISTJ", "ESFP"], "conflict": ["INTP", "INTJ"]},
  "ISTP": {"best": ["ESTP", "ISFP", "ISTJ"], "conflict": ["ENFJ", "ESFJ"]},
  "ISFP": {"best": ["ESFP", "ENFJ", "ISFJ"], "conflict": ["ENTJ", "ESTJ"]},
  "ESTP": {"best": ["ISTP", "ESFP", "ENTP"], "conflict": ["INFJ", "INFP"]},
  "ESFP": {"best": ["ISFP", "ESFJ", "ESTP"], "conflict": ["INTJ", "ISTJ"]},
}

UI_TEXT = {
  "zh": {
    "brandTitle": "精神状态速测台",
    "brandSub": "48题四选一 · 搞笑但有参考性",
    "homeTitle": "今天测测你的人间操作系统",
    "homeLead": "48 道情景题，每题 4 个离谱选项 + 一条金句。答完给你认真分析、人间锐评、职业方向、恋爱匹配，还能翻增强图鉴。",
    "startBtn": "开始快问快答",
    "previewTypes": "先看 16 型图鉴",
    "nickTitle": "给自己起个节目名",
    "nickLead": "会出现在结果和海报上。不填就叫“匿名选手”。",
    "nickPlaceholder": "例如：已读不回仙人、DDL魔法师",
    "nickSubmit": "进入答题",
    "nickBack": "回首页",
    "analysisTip": "认真分析",
    "snarkTip": "人间锐评",
    "matchHint": "最合拍 3 · 高摩擦 2",
    "careersTitle": "适合去哪搬砖",
    "matchesTitle": "恋爱 / 社交匹配",
    "fantasyTitle": "幻想职业",
    "animalTitle": "动物搭子",
    "backHomeFromTypes": "回首页",
    "homeDisclaimer": "娱乐向自我探索，有参考性但不构成专业心理评估。手机也能顺畅作答。",
    "soundOn": "音效开",
    "soundOff": "音效关",
    "about": "关于",
    "restart": "重测",
    "prev": "上一题",
    "homeFromQuiz": "回首页",
    "progress": "第 {cur} / {total} 题",
    "copyShare": "复制分享文案",
    "nativeShare": "系统分享",
    "retry": "再来一次",
    "generatePoster": "生成海报",
    "downloadSquare": "下载 1:1",
    "downloadTall": "下载 9:16",
    "close": "关闭",
    "copied": "已复制",
    "typesTitle": "16 型增强图鉴",
    "typesLead": "关键词、优势、注意点、成长建议、口头禅、幻想职业和动物搭子都在。",
    "feature1Title": "选项够损才真实",
    "feature1Text": "电梯社死、DDL神学、群聊政治、语音条、团建命运，专治“我都差不多”。",
    "feature2Title": "结果更有参考性",
    "feature2Text": "维度占比 + 优势/注意点 + 职业 + 匹配 + 双尺寸海报。",
    "feature3Title": "手机也能玩",
    "feature3Text": "单列选项、大按钮、可局域网访问。",
    "aboutTitle": "关于精神状态速测台",
    "aboutBody": "纯前端趣味 MBTI 风格测试。48 题四选一，结果只存在你的浏览器本地。同一 Wi-Fi 下可用手机访问电脑显示的局域网地址。",
    "researcher": "场控小喇叭",
    "researcherLine": "我是小喇叭。每题送你一句金句，选完再把你的选项翻译成人话。",
    "traitsTitle": "关键词",
    "strengthsTitle": "优势雷达",
    "watchoutsTitle": "注意点",
    "growthTitle": "成长建议",
    "sloganTitle": "口头禅",
    "codexOpen": "看完整图鉴卡",
    "referenceNote": "本结果基于四维偏好统计，适合自我观察与社交娱乐参考。"
  },
  "en": {
    "brandTitle": "Mood Stage Quiz",
    "brandSub": "48Q · 4 choices · funny + useful",
    "homeTitle": "Scan your human operating system",
    "homeLead": "48 situational questions, 4 unhinged options + a quote each. Then analysis, snark, careers, matches, and an upgraded codex.",
    "startBtn": "Start rapid-fire",
    "previewTypes": "Browse 16-type codex",
    "nickTitle": "Pick a stage name",
    "nickLead": "Shows on results and posters. Blank = Anonymous Player.",
    "nickPlaceholder": "e.g. Read-but-silent immortal",
    "nickSubmit": "Enter quiz",
    "nickBack": "Home",
    "analysisTip": "Serious Analysis",
    "snarkTip": "Snark Mode",
    "matchHint": "Best 3 · Friction 2",
    "careersTitle": "Career directions",
    "matchesTitle": "Love / social match",
    "fantasyTitle": "Fantasy job",
    "animalTitle": "Animal buddy",
    "backHomeFromTypes": "Home",
    "homeDisclaimer": "Fun self-exploration with practical reference—not a clinical assessment. Mobile-friendly.",
    "soundOn": "Sound On",
    "soundOff": "Sound Off",
    "about": "About",
    "restart": "Retest",
    "prev": "Prev",
    "homeFromQuiz": "Home",
    "progress": "Q {cur} / {total}",
    "copyShare": "Copy share text",
    "nativeShare": "Share",
    "retry": "Again",
    "generatePoster": "Make posters",
    "downloadSquare": "Download 1:1",
    "downloadTall": "Download 9:16",
    "close": "Close",
    "copied": "Copied",
    "typesTitle": "16-Type Upgraded Codex",
    "typesLead": "Keywords, strengths, watchouts, growth tips, slogans, fantasy jobs, animal buddies.",
    "feature1Title": "Mean options, real you",
    "feature1Text": "Elevator cringe, deadline theology, groupchat politics, voice notes, team-building fate.",
    "feature2Title": "More reference value",
    "feature2Text": "Axis mix + strengths/watchouts + careers + matches + dual posters.",
    "feature3Title": "Works on phones",
    "feature3Text": "Single-column choices, big taps, LAN access supported.",
    "aboutTitle": "About Mood Stage Quiz",
    "aboutBody": "Pure front-end fun MBTI-style test. 48 questions, 4 choices. Results stay local. On the same Wi-Fi, open the LAN URL shown by the server on your phone.",
    "researcher": "Stage Horn",
    "researcherLine": "I’m Horn. One quote per question, then I translate your choices into human language.",
    "traitsTitle": "Keywords",
    "strengthsTitle": "Strengths",
    "watchoutsTitle": "Watchouts",
    "growthTitle": "Growth tip",
    "sloganTitle": "Catchphrase",
    "codexOpen": "Open full codex card",
    "referenceNote": "Result is preference stats across four axes—good for self-observation and social fun."
  }
}

assert len(QUESTIONS) == 48
assert all(len(q["options"]) == 4 and q.get("quote") for q in QUESTIONS)
axes = {}
for item in QUESTIONS:
    axes[item["axis"]] = axes.get(item["axis"], 0) + 1
assert axes == {"EI": 12, "SN": 12, "TF": 12, "JP": 12}, axes

out = (
    dump("QUESTIONS", QUESTIONS)
    + "\n"
    + dump("TYPES", TYPES)
    + "\n"
    + dump("CAREERS", CAREERS)
    + "\n"
    + dump("MATCHES", MATCHES)
    + "\n"
    + dump("UI_TEXT", UI_TEXT)
)
(ROOT / "data.js").write_text(out, encoding="utf-8")
print("data.js", len(QUESTIONS), "bytes", len(out.encode("utf-8")))
